<project name="MyInfArithProject" basedir="." default="run">

    <property name="src.dir" value="."/>
    <property name="build.dir" value="build"/>
    <property name="main.class" value="MyInfArith"/>

    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

    <target name="init">
        <mkdir dir="${build.dir}"/>
    </target>

    <target name="compile" depends="init">
        <javac srcdir="${src.dir}" destdir="${build.dir}" includeantruntime="false"/>
    </target>

    <target name="run" depends="compile">
        <java classname="${main.class}" fork="true" dir="${build.dir}">
            <arg value="int"/>
            <arg value="add"/>
            <arg value="123"/>
            <arg value="456"/>
        </java>
    </target>

</project>
